name: freedom
description: Record your life, review when you have time.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.6+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: 1.8.0
  hive: 2.0.4

  cupertino_icons: 1.0.3
  #get: 4.3.8
  get: 4.5.0
  image_picker: 0.8.3+2
  #flutter_image_compress: 1.1.0
  image: 3.2.0
  #fast_image_resizer: 0.0.2
  intl: 0.17.0
  clipboard: 0.1.3
  fluttertoast: 8.0.7
  share: 2.0.4
  receive_sharing_intent: 1.4.5
  path_provider: 2.0.2
  sqflite: 2.2.2
  sqflite_common_ffi: 2.2.2
  sqlite3: 2.1.0
  sqlite3_flutter_libs: 0.5.15
  flutter_easyloading: 3.0.5
  pull_to_refresh: 2.0.0
  easy_debounce: 2.0.2+1
  auto_size_text: 3.0.0
  flutter_screenutil: 5.9.0
dev_dependencies:
  #flutter_launcher_icons: 0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/freedom.png"
#flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700